common: &common
  adapter: postgresql
  username: 
  password: 

development:
  <<: *common
  database: counter_development

test:
  <<: *common
  database: counter_test

production:
  <<: *common
  database: counter_production